### ISSUE TITLE
Feature request: Cloth state menu in character creator

### ISSUE THREAD

**Issue by RndUser0** [FairBear/CareBairPackage#1]
Hello FairBear, thank you for this awesome plugin.
Could you please make the cloth state menu available in the character creator via a hotkey?
I'd highly appreciate that.

**Comment by FairBear** [comment]
Will try to add.

**Comment by FairBear** [comment]
I'll be adding this in Agent Trainer instead since its much more convenient. Would that be okay?

**Comment by RndUser0** [comment]
Yeah, works fine, thank you!
